/* MyEFF 2.0 — landing: chapters load from the database (falls back to the built-in list if offline). */
(function(){
  const fallback=[['EFF at Louisiana State University','Louisiana State University','Baton Rouge, LA','LA','chapter'],['EFF at Delaware State University','Delaware State University','Dover, DE','DE','chapter'],['EFF at Xavier University of Louisiana','Xavier University of Louisiana','New Orleans, LA','LA','chapter'],['EFF at Howard University','Howard University','Washington, DC','DC','chapter'],['EFF at Norfolk State University','Norfolk State University','Norfolk, VA','VA','chapter'],['EFF at Tallahassee State College','Tallahassee State College','Tallahassee, FL','FL','chapter'],['EFF at Savannah State University','Savannah State University','Savannah, GA','GA','chapter'],['EFF at Clark Atlanta University','Clark Atlanta University','Atlanta, GA','GA','chapter'],['EFF at Albany State University','Albany State University','Albany, GA','GA','chapter'],['EFF at Virginia State University','Virginia State University','Petersburg, VA','VA','chapter'],['EFF at Kentucky State University','Kentucky State University','Frankfort, KY','KY','chapter'],['EFF at Tuskegee University','Tuskegee University','Tuskegee, AL','AL','chapter'],['EFF at Florida International University','Florida International University','Miami, FL','FL','chapter'],['EFF at UNC Greensboro','University of North Carolina at Greensboro','Greensboro, NC','NC','chapter'],['EFF at Sam Houston State University','Sam Houston State University','Huntsville, TX','TX','chapter'],['Pretty Girls Who Serve — Delaware State University','Delaware State University','Dover, DE','DE','pgws'],['Pretty Girls Who Serve — Norfolk State University','Norfolk State University','Norfolk, VA','VA','pgws']];
  const grid=document.getElementById('chapterGrid');if(!grid)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let chapters=fallback;
  function render(state='all'){grid.innerHTML=chapters.filter(c=>c[4]!=='national'&&(state==='all'||c[3]===state)).map(c=>`<article class="chapter"><span class="badge">EFF</span><h3>${esc(c[0])}</h3><p>${esc(c[1])}<br>${esc(c[2])}</p><small>${c[4]==='pgws'?'SISTERHOOD BRANCH':'COLLEGIATE CHAPTER'}</small></article>`).join('')||'<p>No chapters in this state yet — start one.</p>';}
  document.querySelectorAll('#chapterFilters button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#chapterFilters .active').classList.remove('active');b.classList.add('active');render(b.dataset.state)}));
  const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear();
  render();
  const cfg=window.EFF_MEMBER_SUPABASE;
  if(cfg&&cfg.url){fetch(cfg.url+'/rest/v1/eff_chapters?select=name,school,city,state,kind,status&status=neq.dissolved&order=name',{headers:{apikey:cfg.publishableKey,Authorization:'Bearer '+cfg.publishableKey}}).then(r=>r.ok?r.json():null).then(rows=>{if(rows&&rows.length){chapters=rows.map(r=>[r.name,r.school,r.city+', '+r.state,r.state,r.kind]);render(document.querySelector('#chapterFilters .active').dataset.state);const n=document.getElementById('chapterCount');if(n)n.textContent=rows.filter(r=>r.kind!=='national').length;}}).catch(()=>{});}
})();
